### ISSUE TITLE
there should be root

### ISSUE THREAD

**Issue by nydisc** [herrwinfried/EasierWsaInstaller#1]
**yes** @herrwinfried

**Comment by nydisc** [comment]
@herrwinfried

**Comment by nydisc** [comment]
@herrwinfried

**Comment by nydisc** [comment]
@herrwinfried

**Comment by nydisc** [comment]
@herrwinfried

**Comment by nydisc** [comment]
sorry for tagging @herrwinfried multiple times. git said message unsent

**Comment by nydisc** [comment]
anyways, what about the root?

**Comment by herrwinfried** [comment]
I did not understand

**Comment by herrwinfried** [comment]
> anyways, what about the root?

@nydisc What we call root. You can think of it as an administrator account in windows. but you'll see it more often on android or linux instead of windows and they call it root or you can see superuser etc. naming.
